### ISSUE TITLE
Questions about "Weeks of Debugging Can Save You Hours of TLA+"

### ISSUE THREAD

**Issue by PineWu** [lemmy/BlockingQueue#1]
Hi, Kuppe:
I have read your great talk presentation from here：
https://bitbucket.org/lemmster/blockingqueue

But I have a little confused about the state graph in “BlockingQueue in PlusCal” section，as attached.
![image](https://user-images.githubusercontent.com/1628462/80330331-785bf680-8877-11ea-8c50-00eff32e5438.png)

Highlighted in red box.
**If the "p1" is already in the waitset, the 'put' action should not occur because we have only one producer and it is blocked  now.**
PS: the state graph in this git project has no such action.

I’m not sure if my understanding is correct or if that PDF is out of date.
Please help. Thanks

**Comment by lemmy** [comment]
Thanks for reporting, the PDF at bitbucket is outdated.  To avoid future confusion, I made that repo private.

**Comment by PineWu** [comment]
Got it, thanks
